title: "阪大将棋部HP"
description: "阪大将棋部の公式ホームページです。"
theme: jekyll-theme-cayman
markdown: kramdown
nav:
  - name: "トップ"
    link: "/"
  - name: "部員紹介"
    link: "docs/members/"
  - name: "大会結果"
    link: "docs/events/"
  - name: "活動について"
    link: "docs/about/"
  - name: "リンク集"
    link: "docs/links/"
  - name: "お問い合わせ"
    link: "docs/contact/"
  
